### PR TITLE
Add French holidays

### PR DESCRIPTION
**Pull request by oiffrig**

### CODE REVIEW

**Comment by Diaoul** [comment]
I was looking for this, you beat me to it. Nice work.

**Comment by chimpy** [comment]
Would love to see this merged!

**Comment by jacques-hybrid** [comment]
@oiffrig is there any progress on this pull request ?
Thanks

**Comment by lopezco** [comment]
@ryanss could you merge this pull request?

**Comment by jrmi** [comment]
Up ?

**Comment by Diaoul** [comment]
Up ?

**Pull request merged**
