### PR TITLE
Cumulative merge commit - v.0.9 candidate

### PR DESCRIPTION
**Pull request by dr-prodigy**
Hi, seeing that the project has been idle for some months, along with my contribution on italian holidays, I decided to put some extra work, so I merged the largest part of the previously pull-requested branches which have provided good test coverage and passed all travis checks.

Added a lot of national holidays on queue and support for python3.6: see changelog for details.

Possible candidate for v.0.9 lib (?).

### CODE REVIEW

**Comment by kirpit** [comment]
Hi @ryanss ,

What's the possibility getting this and other awaiting PRs in? If you're too busy to maintain this package, would you please consider giving write access to one of the contributors so we can move on?

Cheers.

**Comment by ggravlingen** [comment]
Has someone tried mailing @ryanss too? Perhaps he's not monitoring github these days?

**Comment by dswah** [comment]
@dr-prodigy good work on this PR

i just emailed @ryanss about the project. 
Hopefully we get a response.

otherwise, how can we keep this project going?
perhaps @dr-prodigy you can make your fork into a separate project (like python-holidays-2) and create another pypi module.

cc @ggravlingen @kirpit

**Comment by ryanss** [comment]
Unfortunately, I do not have time to maintain this project any more. I would be happy to transfer it to another Github user and provide the PyPI info.

@dr-prodigy Would you be willing to take on this project?

**Comment by ggravlingen** [comment]
@ryanss @dr-prodigy I'm happy to help out too. I'm adminestring the repo for pytradfri (a Python lib to communicate with IKEA's smart light devices) so I've got some experience.

**Comment by dr-prodigy** [comment]
Thank you all very much.. Not a so special work, just some careful good ol'
merging after all :)

I'd surely love to keep up the project.. Not sure if I'll be able to do it
for long, but for the moment I'm at disposal.

Patrik could also help us.

@ryanss / @all: Please let me know what should I/we do, and any other
interesting information about the next steps.

Cheers guys!
Mauri



Il 13 gen 2018 7:29 PM, "Patrik" <notifications@github.com> ha scritto:

@ryanss <https://github.com/ryanss> @dr-prodigy
<https://github.com/dr-prodigy> I'm happy to help out too. I'm adminestring
the repo for pytradfri (a Python lib to communicate with IKEA's smart light
devices) so I've got some experience.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ryanss/python-holidays/pull/84#issuecomment-357456035>,
or mute the thread

**Comment by ryanss** [comment]
@dr-prodigy I can't transfer the `python-holidays` project from my GitHub account to your GitHub account because you already have a repository named `python-holidays` under your user. I've added you to collaborators list so you can push to `ryanss/python-holidays`. You can go ahead and merge any commits from your own branch to mine and once that's complete please delete python-holidays from your user and then I'll be able to transfer the project. Thanks!

**Comment by ggravlingen** [comment]
🎉🎉🎉

**Comment by dr-prodigy** [comment]
Cheeers :)

2018-01-14 14:05 GMT+01:00 Patrik <notifications@github.com>:

**Comment by ggravlingen** [comment]
Will you push to pypi as well?

**Comment by dr-prodigy** [comment]
@ryanss

Hi! Okay, I should be done with everything.. I moved to v0.9 and finally to
0.9.1 due to some additional fixes, PR and issue fixes I wanted to include.

If everything looks in shape, I can proceed in dropping my personal fork..
please let me know!

One last thing.. if everything is ok I would like, of course, to publish to
pypi too, but I don't have any experience about that (especially because
you're currently the project owner, and this probably make things harder)..
how can I / we arrange this?

..Thank you very much!

2018-01-13 21:08 GMT+01:00 ryanss <notifications@github.com>:

**Comment by dr-prodigy** [comment]
That's what I'd like to do, of course.. just asked some info to ryanss in
order to do it..

2018-01-14 17:02 GMT+01:00 Patrik <notifications@github.com>:

**Comment by ggravlingen** [comment]
It's not that tricky to push. You setup credentials in a file in your user home, cd to the project folder, issue a one-line command and bam, you're on pypi. 😊

**Comment by ryanss** [comment]
@dr-prodigy Amazing work getting all the pull requests sorted. Please send an email to the email listed on my GitHub profile so I have your email and I will send you the PyPI info and the commands I use to publish. Make sure there's no unmerged code in your fork and delete it from your user profile so I can transfer the project to you. Thanks so much!

**Pull request merged**
