### PR TITLE
Update Python versions: add 3.6, remove EOL

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/ryanss/python-holidays/issues/56.

Python 3.2 is causing build problems (#56) and it's been decided it's easiest to drop it as it's EOL and no longer receiving security updates.

Now is also a good time to add Python 3.6 and remove the other EOL versions (2.5, 2.6, 3.2 and 3.3), which allows the code to be modernised.

Here's the pip installs for holidays from PyPI for the last month:
```
$ pypinfo --percent --pip holidays pyversion
python_version percent download_count
-------------- ------- --------------
2.7              70.7%         11,946
3.6              19.7%          3,332
3.5               7.3%          1,239
3.4               2.2%            376
2.6               0.0%              3
3.3               0.0%              1
```

Those versions are barely used if at all.

### CODE REVIEW

**Comment by hugovk** [comment]
I've tacked https://github.com/ryanss/python-holidays/pull/80 onto this and now the build passes.

**Comment by dr-prodigy** [comment]
Superseded by **1452cc3** : please refresh your repo and re-apply small fixes not related to python version. Thx!

**Comment by hugovk** [comment]
@dr-prodigy The main point of this PR is to remove those Python versions which are EOL ((2.5, 2.6, 3.2 and 3.3), and then update the code to ease the maintenance burden and make use of more modern Python.

Here's updated pip installs for holidays from PyPI for the last month (via `pypinfo --percent --pip --markdown holidays pyversion`):

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   76.0% |         16,846 |
| 3.6            |   18.9% |          4,194 |
| 3.5            |    3.6% |            796 |
| 3.4            |    1.5% |            332 |
| 2.6            |    0.0% |              2 |
| 3.7            |    0.0% |              1 |

Of the EOL versions, this shows only two installs for 2.6, and nothing for 2.5, 3.2 and 3.3.

**Comment by hugovk** [comment]
See PR https://github.com/ryanss/python-holidays/pull/92!

**Pull request closed without merging**
