### PR TITLE
Add french holidays

### PR DESCRIPTION
**Pull request by lopezco**
Add code and tests

### CODE REVIEW

**Comment by jacques-hybrid** [comment]
@lopezco is there any progress on this pull request ?
Thanks

**Comment by lopezco** [comment]
@jacques-hybrid sorry I didn't check the travis errors
I will make the necessary changes.

**Comment by lopezco** [comment]
@jacques-hybrid the remaining errors are dependencies issues... I think

**Comment by lopezco** [comment]
Actually, I just saw that this pull request is more detailed than mine
https://github.com/ryanss/python-holidays/pull/48

I think it should be merged

**Pull request closed without merging**
