### PR TITLE
Italian holidays

### PR DESCRIPTION
**Pull request by dr-prodigy**
Commit completed with unit tests, added refinements on national holidays in history

### CODE REVIEW

**Comment by dr-prodigy** [comment]
needed some fixes on old code and libs to pass checks (e.g.: flake8 3.5.0 fails with syntax error)

**Comment by aventrax** [comment]
Hello, how about the local saint patron of the cities (not province, just city)?

**Comment by dr-prodigy** [comment]
Hi, theoretically every town, even the very small ones, has its own patron.
Practically, speaking bank holiday, the most majority of them choose to honor their province's saint.

So to complete the whole work we should provide all provinces' saints:
https://it.wikipedia.org/wiki/Santi_patroni_cattolici_delle_citt%C3%A0_capoluogo_di_provincia_italiane

Not a complex work, just a matter of adding names and dates. Maybe I'll be doing it in some days.

**Comment by dr-prodigy** [comment]
This pull request has been superseded by a cumulative merge push so I close it.

**Pull request closed without merging**
