### PR TITLE
Add Finnish holidays

### PR DESCRIPTION
**Pull request by Ardetus**

### CODE REVIEW

**Comment by dr-prodigy** [comment]
Please check and re-submit. Thx!

**Comment by Ardetus** [comment]
I agree that eves are kind of holidays in Finland and day offs for some people, but I understood that this library was for counting holidays, not day offs or flag days.

[Public holidays in Finland](https://en.wikipedia.org/wiki/Public_holidays_in_Finland)

**Comment by hugovk** [comment]
Flag days are definitely not eligible.

I think those two eves are important enough to be listed as holidays. That Wikipedia page agrees:

> Christmas Eve and Midsummer Eve might very well be the single most important holidays during the entire year for Finns. Surprisingly they are not officially called holidays and are not so marked in calendars, but for most people, are not working days, and in practice they differ from official holidays only in that most shops are open on those days from early morning till noon. They hold this de facto status partly due to some statements in legislation but also because most employment contracts provides for these days as full holidays.

And lists them:

image


From a practical point of view, they should be included.

Likewise, even though "All Sundays" are official holidays, from a practical point of view they should not be included.

**Comment by Ardetus** [comment]
It's true that those eves are even more important holidays, than some of official holidays for majority of Finns. I just made new PR including those two eves.

**Pull request closed without merging**
